### ISSUE TITLE
Parallel builds

### ISSUE THREAD

**Issue by danielcompton** [jaunt-lang/jaunt#24]
Circle CI gives us 4 machines to work with, lets use them to their fullest!

Clojure runs their tests with `mvn clean test`. 

It looks like more deps are getting downloaded after `dependency:go-offline` when `test` is run which seems to be significantly slowing down tests, as they aren't included in the Circle m2 cache.

**Comment by arrdem** [comment]
Presuming that we're using the `ant` interface, there are two test paths, `test-example` and `test-generative` which could both depend on `init` and could be run in parallel. That's probably the first and best opportunity for parallelism in the build process, since those test suites account for probably 40% each of time spent building. Looks like CircleCI already has a [decent writeup](https://circleci.com/docs/parallel-manual-setup) on how to do that sort of thing, but I'm a little bit put off by the fact that we manually have to do task partitioning.
